config/routes.rb
Rails.application.routes.draw do
  resources :teams
  get 'dashboard/index'

  resources :features


  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :team, optional: true

  before_save :set_team
  before_save :remove_previous

  def humanize
    durr = duration
    [[60, :seconds], [60, :minutes], [24, :hours], [30, :days], [1000, :months]].map{ |count, name|
      if durr > 0
        durr, n = durr.divmod(count)
        "#{n.to_i} #{name}"
      end
    }.compact.reverse.join(' ')
  end

  def set_team
    team_name = name.match(/^[^-|_]*/).to_s
    team_name = "CUOA" if team_name == "COB"
    self.team_id = Team.find_by(code: team_name).id
  end

  def remove_previous
    previous = Feature.where(name: name, platform: platform)
    previous.delete_all
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :features
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @teams = Team.all
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_feature, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /features
  # GET /features.json
  def index
    @features = Feature.all
  end

  # GET /features/1
  # GET /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url, notice: 'Feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:name, :duration, :platform)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/application/_card.html.slim
ul.collection.with-header.card
  li.collection-header
    .row
      .col.s2
        = image_tag("https://s3-eu-west-1.amazonaws.com/frikandelenstein/teams/#{team.code}.png", height: "100", class: "responsive-img")
    h4= team.name
  - if team.features.count == 0
    .center
      = image_tag("https://media.giphy.com/media/JfDNFU1qOZna/giphy.gif", class: "responsive-img")

  - else
    - team.features.each do |feature|
      li.collection-item
        h5= feature.name
        span.badge= feature.platform
        p= feature.humanize

app/views/application/_nav.html.slim
nav
  .nav-wrapper
    .col.s12
      = link_to root_path, class: "brand-logo" do
        = image_tag "logoo.png", class: "logo-img", height: "100"

      ul.right.hide-on-med-and-down
        li
          = link_to "Teams", teams_path
        li
          = link_to "Features", features_path

app/views/application/nav.html.slim
nav
  .nav-wrapper
    a href="#" class="brand-logo" Logo
    ul id="nav-mobile" class="right hide-on-med-and-down"
      li
        a href="sass.html" Sass
      li
        a href="badges.html" Components
      li
        a href="collapsible.html" JavaScript

app/views/dashboard/index.html.slim
.row
  - @teams.each do |team|
    .col.s12
      = render partial: "card", locals: { team: team }

app/views/features/_form.html.erb
<%= form_with(model: feature, local: true) do |form| %>
  <% if feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% feature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :feature_name %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, id: :feature_duration %>
  </div>

  <div class="field">
    <%= form.label :platform %>
    <%= form.text_field :platform, id: :feature_platform %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing Feature</h1>

<%= render 'form', feature: @feature %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<div class="row">
  <div class="col s12">
    <h1>Features</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Duration</th>
          <th>Platform</th>
          <th>Team</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @features.each do |feature| %>
          <tr>
            <td><%= feature.name %></td>
            <td><%= feature.duration %></td>
            <td><%= feature.platform %></td>
            <td><%= feature.team.try(:name) %></td>
            <td><%= link_to 'Show', feature %></td>
            <td><%= link_to 'Edit', edit_feature_path(feature) %></td>
            <td><%= link_to 'Destroy', feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Feature', new_feature_path %>
  </div>
</div>

app/views/features/new.html.erb
<h1>New Feature</h1>

<%= render 'form', feature: @feature %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feature.name %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @feature.duration %>
</p>

<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monidor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "nav" %>
    <%= yield %>
  </body>
</html>